
[General]
	#List of rules in format "domain:item1, domain:item2, n".
	#Causes a compacting drawer convert n of item1 into 1 of item2.
	compactingRules = [
		"minecraft:clay, minecraft:clay_ball, 4",
		"minecraft:charcoal, morecharcoal:charcoal_chunk, 8",
		"minecraft:coal, morecharcoal:coal_chunk, 8",
		"minecraft:warped_wart_block, nether_extension:warped_wart, 4"
	]
	enableUI = true
	debugTrace = false
	enableItemConversion = true
	enableSidedInput = true
	#The number of item stacks held in a basic unit of storage.
	#1x1 drawers hold 8 units, 1x2 drawers hold 4 units, 2x2 drawers hold 2 units.
	#Half-depth drawers hold half those amounts.
	baseStackStorage = 16
	enableExtraCompactingRules = true
	#Range: 1 ~ 50
	controllerRange = 24
	enableSidedOutput = true

[StorageUpgrades]
	level2Mult = 16
	#Storage upgrades multiply storage capacity by the given amount.
	#When multiple storage upgrades are used together, their multipliers are added before being applied.
	level1Mult = 8
	level3Mult = 32
	level5Mult = 128
	level4Mult = 64

[Integration]
	wailaStackRemainder = true

