
[general]
	blacklisted_screens = ["curios", "refinedstorage", "dankstorage", "ironfurnaces"]
	swap_hands = true
	debug_as_level_info = false
	#Allowed Values: LEFT, RIGHT
	slots_side = "LEFT"
	#Range: 0 ~ 128
	slots_margin = 2
	on_debug = false

