[[curiosSettings]]
  identifier = "back"
  size = 2
[[curiosSettings]]
  identifier = "charm"
  size = 2
[[curiosSettings]]
  identifier = "ring"
  size = 10
[[curiosSettings]]
  identifier = "head"
  size = 1
